name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Eslint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test